DELETE http://localhost:3001/api/persons/2 HTTP/1.1

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "test",
    "number": "98494949513"
}

###

GET http://localhost:3001/api/persons